language: ruby
# only run CI-builds on master branch
branches:
  only:
  - master
rvm:
- 2.3.8
# set execution permission on our build script
before_script:
 - chmod +x ./scripts/cibuild

before_install:
  - gem update --system
  - gem install bundler

# path to our build script. 
# Travis will run `bundle install` by default before running our script
script: ./scripts/cibuild
exclude: [vendor]
sudo: false